# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_data <- function(filename, ids) {
    .Call('_bfread_get_data', PACKAGE = 'bfread', filename, ids)
}

get_ngrams <- function(filename) {
    .Call('_bfread_get_ngrams', PACKAGE = 'bfread', filename)
}

read_column <- function(filename, col_number, delimiter) {
    .Call('_bfread_read_column', PACKAGE = 'bfread', filename, col_number, delimiter)
}

read_delim <- function(filename, delim) {
    .Call('_bfread_read_delim', PACKAGE = 'bfread', filename, delim)
}

read_sql <- function(filename, table, get_columns) {
    .Call('_bfread_read_sql', PACKAGE = 'bfread', filename, table, get_columns)
}

